package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;

import java.security.PrivilegedActionException;
import java.util.function.DoubleSupplier;

import frc.robot.subsystems.Elevator_Drive;

public class Climber_Down extends Command {

        private final Elevator_Drive m_elevator_Drive;
        private DoubleSupplier m_elevatorspeed;

    public Climber_Down(Elevator_Drive Subsystem) {

        m_elevator_Drive = Subsystem;
        addRequirements(m_elevator_Drive);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        //double elevatorspeed = m_elevatorspeed.getAsDouble();
            m_elevator_Drive.Elevatormove(-0.75);
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
